apiVersion: v1
kind: Service
metadata:
  name: simpson-stg-web-service
  namespace: simpson-videochat
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8002
  selector:
    app: simpson-stg-web
